# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pedido.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pedido.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpedido.proto\x12\x06pedido\"\xb8\x01\n\rPedidoRequest\x12\x15\n\remail_cliente\x18\x01 \x01(\t\x12\x10\n\x08producto\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\x12\x15\n\rpasarela_pago\x18\x04 \x01(\t\x12\r\n\x05\x62\x61nco\x18\x05 \x01(\t\x12\x15\n\rmarca_tarjeta\x18\x06 \x01(\t\x12\x11\n\tdireccion\x18\x07 \x01(\t\x12\x0e\n\x06numero\x18\x08 \x01(\t\x12\x0e\n\x06region\x18\t \x01(\t\"0\n\x0ePedidoResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\r\n\x05\x65xito\x18\x02 \x01(\x08\x32P\n\rPedidoService\x12?\n\x0eRealizarPedido\x12\x15.pedido.PedidoRequest\x1a\x16.pedido.PedidoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedido_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEDIDOREQUEST']._serialized_start=25
  _globals['_PEDIDOREQUEST']._serialized_end=209
  _globals['_PEDIDORESPONSE']._serialized_start=211
  _globals['_PEDIDORESPONSE']._serialized_end=259
  _globals['_PEDIDOSERVICE']._serialized_start=261
  _globals['_PEDIDOSERVICE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
